server:
  port: 8081
  servlet:  
    context-path: /api/personal
  
spring:
  datasource:
    url: ${dburl:jdbc:mysql://localhost:3306/personal_website_blogs?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&preferredTestQuery=select now()}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${dbusername:root}
    password: ${dbpassword:qsr123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy
  application: 
    name: personal-website-blogs  
  data:  
    rest:  
      base-path: /rest